/*
 * generated by Xtext 2.25.0
 */
package br.ufes.inf.nemo.teep.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TptpUiModule extends AbstractTptpUiModule {

	public TptpUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
