/*
 * generated by Xtext 2.25.0
 */
package br.ufes.inf.nemo.teep.ide;

import br.ufes.inf.nemo.teep.TptpRuntimeModule;
import br.ufes.inf.nemo.teep.TptpStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class TptpIdeSetup extends TptpStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new TptpRuntimeModule(), new TptpIdeModule()));
	}
	
}
