/*
 * generated by Xtext 2.25.0
 */
package br.ufes.inf.nemo.teep;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class TptpStandaloneSetup extends TptpStandaloneSetupGenerated {

	public static void doSetup() {
		new TptpStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
