/*
 * generated by Xtext 2.25.0
 */
package br.ufes.inf.nemo.teep;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TptpRuntimeModule extends AbstractTptpRuntimeModule {
}
